In [1]:
#import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from scipy import stats
import statsmodels.api as sm
from sklearn.metrics import accuracy_score
import seaborn as sns

%matplotlib inline

In [84]:
import numpy as np
import pandas as pd


class logFile:
    
    def __init__(self,file):
        self.df = pd.read_csv(file, usecols = ['ip','date','time','accession'])
        self.original_df = self.df
        
    def extract(self):
        return self.df
    
    def transformer(self,df):
        self.df = df
        '''
        cleans the data for further manipulation
        input: df
        output: transformed df
        '''
        #setting the datetime
        self.df['datetime'] = self.df['date'] + ' ' + self.df['time']
        self.df['datetime'] = pd.to_datetime(self.df['datetime'])
        
        #Resetting to DatetimeIndex
        self.df = df.set_index(df.datetime)
        #self.df = df.drop('datetime',axis=1)
        
        #Feature Engineering for Filtering
        
        ## Creating cumulative count columns
        self.df['ip_ccount'] = self.df.groupby(self.df.accession).cumcount()+1
        self.df['doc_ccount'] = self.df.groupby(self.df.accession).cumcount()+1
        
        ## Creating total count columns
        self.df['ip_total_count'] = self.df.groupby(self.df.ip, sort=False)['ip_ccount'].transform(max)
        self.df['doc_total_count'] = self.df.groupby(self.df.accession, sort=False)['doc_ccount'].transform(max)
        
        return self.df
    
    def filters(self):
        #return df.query('200 > ip_total_count > 5 and 200 > doc_total_count > 30 ', inplace=True)
    
    def stats(self):
#         self.unique_events = self.df.shape[0]
        
        #Results of filtering
        #sample size
        #loss % of unique docs
        #loss % of unique ips
    
    def plot_stats(self):
#         plt.hist(df1.ip_total_count)
#         plt.hist(df1.doc_total_count)
    
    def graph(self, data):
        pass
    
    def metrics(self, data):
        pass

In [85]:
log = logFile('~/SageMaker/CreatingIPProfiles/log20101010.csv')

In [86]:
df = log.extract()

In [87]:
df1 = log.transformer(df)

In [88]:
df1.head()

,ip,date,time,accession,datetime,ip_ccount,doc_ccount,ip_total_count,doc_total_count
datetime,,,,,,,,,
2010-10-10,108.5.109.gch,2010-10-10,00:00:00,0000950137-01-501552,2010-10-10,1,1,32,2
2010-10-10,108.5.109.gch,2010-10-10,00:00:00,0000950137-01-503045,2010-10-10,1,1,32,1
2010-10-10,108.5.109.gch,2010-10-10,00:00:00,0000950137-01-501552,2010-10-10,2,2,32,2
2010-10-10,209.223.222.jdd,2010-10-10,00:00:00,0001209191-10-049878,2010-10-10,1,1,22730,11341
2010-10-10,209.223.222.jdd,2010-10-10,00:00:00,0001144204-10-053151,2010-10-10,1,1,22730,11383

In [ ]:
# TThings to be cleaned